const adjectives = [
    "Innovative",
    "Sustainable",
    "Inclusive",
    "Cost-Effective",
    "Culturally Sensitive",
    "Futuristic",
    "Human-Centric",
    "Retro",
    "Risk-Taking",
    "Minimalistic",
    "Practical",
    "Artistic",
    "Scientific",
    "Technological",
    "Health-Oriented",
    "Educational",
    "Community-Focused",
    "Environmentally Friendly",
    "Whimsical",
    "Groundbreaking",
    "Luxurious",
    "Thrifty",
    "Nostalgic",
    "Avant-garde",
    "Ergonomic",
    "Organic",
    "Spontaneous",
    "Durable",
    "Multicultural",
    "Intuitive",
    "Compact",
    "Aesthetic",
    "User-friendly",
    "Pioneering",
    "Holistic",
    "Vintage",
    "Revolutionary",
    "Adaptive",
    "Dynamic",
    "Collaborative",
    "Rustic",
    "Healing",
    "Zen",
    "Modular",
    "Analytical",
    "Playful",
    "Robust",
    "Time-saving",
    "Intergenerational"
]

export default adjectives;